language: java
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
script:
- mvn clean
- mvn compile
- ./migrate-db
- mvn test
- if [ "$TRAVIS_BRANCH" = "develop" ]; then ./deploy; fi

before_install:
- openssl aes-256-cbc -K $encrypted_4fdf70d187fc_key -iv $encrypted_4fdf70d187fc_iv
  -in id_rsa.enc -out id_rsa -d
